name: Security Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  sca:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        requirements:
          [
            requirements/one-requirements.txt,
            requirements/two-requirements.txt,
            requirements/three-requirements.txt,
          ]
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: True
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          COMMAND: pip install -r ${{ matrix.requirements }}
        with:
          args: --package-manager=pip --file=${{ matrix.requirements }} --command=python3
